version: 2
jobs:
  build_service:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - maven-dependencies-{{ checksum "driftwood-service/pom.xml" }}
          - maven-dependencies-

      - setup_remote_docker

      - run:
          name: "Build and test project"
          working_directory: ~/repo/driftwood-service
          command: |
              mvn clean install -B

      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "driftwood-service/pom.xml" }}

workflows:
  version: 2
  full_build:
    jobs:
      - build_service
